(cl:in-package #:cl-user)


(defpackage #:statistical-learning.tree-protocol
  (:use #:cl #:statistical-learning.aux-package)
  (:nicknames #:statistical-learning.tp #:sl.tp)
  (:intern sl.opt:left sl.opt:right)
  (:export
   #:attribute-indexes
   #:basic-tree-training-parameters
   #:calculate-loss*
   #:calculate-loss*/proxy
   #:contribute-predictions
   #:contribute-predictions*
   #:contribute-predictions*/proxy
   #:contributed-predictions
   #:contributions-count
   #:depth
   #:distance-function
   #:distance-splitter
   #:extract-predictions
   #:extract-predictions*
   #:extract-predictions*/proxy
   #:fill-split-vector
   #:splitter-state
   #:data-point-oriented-splitter
   #:fill-split-vector*
   #:split-result
   #:fill-split-vector*/proxy
   #:force-tree
   #:force-tree*
   #:fundamental-leaf-node
   #:fundamental-node
   #:fundamental-splitter
   #:fundamental-tree-node
   #:random-splitter
   #:fundamental-tree-training-parameters
   #:indexes
   #:initialize-leaf
   #:initialize-leaf/proxy
   #:split-vector
   #:tree-parameters
   #:weight
   #:left-length
   #:right-length
   #:left-score
   #:right-score
   #:leaf-for
   #:leaf-for/proxy
   #:split-result-improved-p
   #:split-result-improved-p/proxy
   #:split-result-accepted-p
   #:split-result-accepted-p/proxy
   #:leafp
   #:leafs-for
   #:left-node
   #:loss
   #:make-leaf
   #:split-using-splitter/proxy
   #:split-using-splitter
   #:random-splitter
   #:make-leaf*
   #:make-leaf*/proxy
   #:make-node
   #:maximal-depth
   #:minimal-difference
   #:minimal-size
   #:optimal-split-point
   #:parallel
   #:pick-split
   #:pick-split*
   #:pick-split*/proxy
   #:point
   #:predictions
   #:random-attribute-splitter
   #:requires-split-p
   #:requires-split-p/proxy
   #:right-node
   #:root
   #:make-tree
   #:split*
   #:split
   #:split-point
   #:split-training-state
   #:split-training-state*
   #:split-training-state*/proxy
   #:split-training-state-info
   #:split-training-state-info/proxy
   #:mins
   #:maxs
   #:hyperplane-splitter
   #:splitter
   #:standard-leaf-node
   #:standard-tree-training-parameters
   #:sums
   #:support
   #:training-state-clone
   #:tree-model
   #:tree-training-state
   #:treep
   #:trials-count
   #:visit-nodes))
